apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vah3ylt8p-nodejs 
  janus-idp.io/tekton: vah3ylt8p-nodejs
  backstage.io/kubernetes-id: vah3ylt8p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vah3ylt8p-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml